config/routes.rb
Rails.application.routes.draw do
  resources :book_tables
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_table.rb
class BookTable < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_tables_controller.rb
class BookTablesController < ApplicationController
  before_action :set_book_table, only: [:show, :edit, :update, :destroy]

  # GET /book_tables
  # GET /book_tables.json
  def index
    @book_tables = BookTable.all
  end

  # GET /book_tables/1
  # GET /book_tables/1.json
  def show
  end

  # GET /book_tables/new
  def new
    @book_table = BookTable.new
  end

  # GET /book_tables/1/edit
  def edit
  end

  # POST /book_tables
  # POST /book_tables.json
  def create
    @book_table = BookTable.new(book_table_params)

    respond_to do |format|
      if @book_table.save
        format.html { redirect_to @book_table, notice: 'Book table was successfully created.' }
        format.json { render :show, status: :created, location: @book_table }
      else
        format.html { render :new }
        format.json { render json: @book_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_tables/1
  # PATCH/PUT /book_tables/1.json
  def update
    respond_to do |format|
      if @book_table.update(book_table_params)
        format.html { redirect_to @book_table, notice: 'Book table was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_table }
      else
        format.html { render :edit }
        format.json { render json: @book_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_tables/1
  # DELETE /book_tables/1.json
  def destroy
    @book_table.destroy
    respond_to do |format|
      format.html { redirect_to book_tables_url, notice: 'Book table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_table
      @book_table = BookTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_table_params
      params.require(:book_table).permit(:Book_Title, :Published_year, :Author_Name, :Author_Date_of_Birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_tables_helper.rb
module BookTablesHelper
end

app/views/book_tables/_form.html.erb
<%= form_with(model: book_table) do |form| %>
  <% if book_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_table.errors.count, "error") %> prohibited this book_table from being saved:</h2>

      <ul>
        <% book_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Book_Title %>
    <%= form.text_field :Book_Title %>
  </div>

  <div class="field">
    <%= form.label :Published_year %>
    <%= form.number_field :Published_year %>
  </div>

  <div class="field">
    <%= form.label :Author_Name %>
    <%= form.text_field :Author_Name %>
  </div>

  <div class="field">
    <%= form.label :Author_Date_of_Birth %>
    <%= form.number_field :Author_Date_of_Birth %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_tables/edit.html.erb
<h1>Editing Book Table</h1>

<%= render 'form', book_table: @book_table %>

<%= link_to 'Show', @book_table %> |
<%= link_to 'Back', book_tables_path %>

app/views/book_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Tables</h1>

<table>
  <thead>
    <tr>
      <th>Book title</th>
      <th>Published year</th>
      <th>Author name</th>
      <th>Author date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_tables.each do |book_table| %>
      <tr>
        <td><%= book_table.Book_Title %></td>
        <td><%= book_table.Published_year %></td>
        <td><%= book_table.Author_Name %></td>
        <td><%= book_table.Author_Date_of_Birth %></td>
        <td><%= link_to 'Show', book_table %></td>
        <td><%= link_to 'Edit', edit_book_table_path(book_table) %></td>
        <td><%= link_to 'Destroy', book_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Table', new_book_table_path %>

app/views/book_tables/new.html.erb
<h1>New Book Table</h1>

<%= render 'form', book_table: @book_table %>

<%= link_to 'Back', book_tables_path %>

app/views/book_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book title:</strong>
  <%= @book_table.Book_Title %>
</p>

<p>
  <strong>Published year:</strong>
  <%= @book_table.Published_year %>
</p>

<p>
  <strong>Author name:</strong>
  <%= @book_table.Author_Name %>
</p>

<p>
  <strong>Author date of birth:</strong>
  <%= @book_table.Author_Date_of_Birth %>
</p>

<%= link_to 'Edit', edit_book_table_path(@book_table) %> |
<%= link_to 'Back', book_tables_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>